-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 22:57:04 2021
-- Model: New Model    Version: 6.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema TrabalhoISBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TrabalhoISBD` ;

-- -----------------------------------------------------
-- Schema TrabalhoISBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrabalhoISBD`;
USE `TrabalhoISBD` ;

-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`Pessoa` (
  `CPF` CHAR(11) NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `sobrenome` VARCHAR(40) NOT NULL,
  `dataNascimento` CHAR(10) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `log` VARCHAR(40) NOT NULL,
  `num` INT NOT NULL,
  `dataCad` DATETIME NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`telefonePessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`telefonePessoa` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`telefonePessoa` (
  `telefone` CHAR(11) NOT NULL,
  `Pessoa_CPF` CHAR(11) NOT NULL,
  INDEX `fk_enderecoPessoa_Pessoa1_idx` (`Pessoa_CPF` ASC),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  PRIMARY KEY (`Pessoa_CPF`),
  CONSTRAINT `fk_enderecoPessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_CPF`)
    REFERENCES `TrabalhoISBD`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`Passageiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`Passageiro` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`Passageiro` (
  `RG` CHAR(9) NOT NULL,
  `Pessoa_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`Pessoa_CPF`),
  UNIQUE INDEX `RG_UNIQUE` (`RG` ASC),
  CONSTRAINT `fk_Passageiro_Pessoa1`
    FOREIGN KEY (`Pessoa_CPF`)
    REFERENCES `TrabalhoISBD`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`Moto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`Moto` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`Moto` (
  `placa` CHAR(7) NOT NULL,
  `ano` CHAR(4) NOT NULL,
  `cor` VARCHAR(10) NOT NULL,
  `dataReg` DATETIME NOT NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`Piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`Piloto` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`Piloto` (
  `CNH` CHAR(11) NOT NULL,
  `placa` CHAR(7) NOT NULL,
  `Pessoa_CPF` CHAR(11) NOT NULL,
  UNIQUE INDEX `CNH_UNIQUE` (`CNH` ASC),
  PRIMARY KEY (`Pessoa_CPF`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  CONSTRAINT `fk_Piloto_Moto`
    FOREIGN KEY (`placa`)
    REFERENCES `TrabalhoISBD`.`Moto` (`placa`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Piloto_Pessoa1`
    FOREIGN KEY (`Pessoa_CPF`)
    REFERENCES `TrabalhoISBD`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`Corrida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`Corrida` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`Corrida` (
  `idcorrida` INT NOT NULL AUTO_INCREMENT,
  `distancia` FLOAT NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `logPartida` VARCHAR(40) NOT NULL,
  `cidadePartida` VARCHAR(30) NOT NULL,
  `estadoPartida` CHAR(2) NOT NULL,
  `logDestino` VARCHAR(40) NOT NULL,
  `cidadeDestino` VARCHAR(30) NOT NULL,
  `estadoDestino` CHAR(2) NOT NULL,
  `dataCorrida` DATETIME NOT NULL,
  `Passageiro_Pessoa_CPF` CHAR(11) NOT NULL,
  `Piloto_Pessoa_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`idcorrida`, `Passageiro_Pessoa_CPF`, `Piloto_Pessoa_CPF`),
  INDEX `fk_Corrida_Passageiro1_idx` (`Passageiro_Pessoa_CPF` ASC),
  INDEX `fk_Corrida_Piloto1_idx` (`Piloto_Pessoa_CPF` ASC),
  CONSTRAINT `fk_Corrida_Passageiro1`
    FOREIGN KEY (`Passageiro_Pessoa_CPF`)
    REFERENCES `TrabalhoISBD`.`Passageiro` (`Pessoa_CPF`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Corrida_Piloto1`
    FOREIGN KEY (`Piloto_Pessoa_CPF`)
    REFERENCES `TrabalhoISBD`.`Piloto` (`Pessoa_CPF`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`Avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`Avaliacao` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `qtdEstrelas` INT NOT NULL,
  `comentario` VARCHAR(50) NULL,
  `Corrida_idcorrida` INT NOT NULL,
  `Corrida_Passageiro_Pessoa_CPF` CHAR(11) NOT NULL,
  `Corrida_Piloto_Pessoa_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacao_Corrida1_idx` (`Corrida_idcorrida` ASC, `Corrida_Passageiro_Pessoa_CPF` ASC, `Corrida_Piloto_Pessoa_CPF` ASC),
  CONSTRAINT `fk_Avaliacao_Corrida1`
    FOREIGN KEY (`Corrida_idcorrida` , `Corrida_Passageiro_Pessoa_CPF` , `Corrida_Piloto_Pessoa_CPF`)
    REFERENCES `TrabalhoISBD`.`Corrida` (`idcorrida` , `Passageiro_Pessoa_CPF` , `Piloto_Pessoa_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoISBD`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabalhoISBD`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `TrabalhoISBD`.`Pagamento` (
  `idPag` INT NOT NULL AUTO_INCREMENT,
  `tipoPagamento` TINYINT NOT NULL,
  `numCartao` CHAR(16) NOT NULL,
  `tipoCartao` TINYINT NOT NULL,
  `codSeguranca` CHAR(3) NOT NULL,
  `dataValidade` CHAR(5) NOT NULL,
  `troco` DECIMAL(5,2) NULL,
  `Corrida_idcorrida` INT NOT NULL,
  `Corrida_Passageiro_Pessoa_CPF` CHAR(11) NOT NULL,
  `Corrida_Piloto_Pessoa_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`idPag`),
  INDEX `fk_Pagamento_Corrida1_idx` (`Corrida_idcorrida` ASC, `Corrida_Passageiro_Pessoa_CPF` ASC, `Corrida_Piloto_Pessoa_CPF` ASC),
  CONSTRAINT `fk_Pagamento_Corrida1`
    FOREIGN KEY (`Corrida_idcorrida` , `Corrida_Passageiro_Pessoa_CPF` , `Corrida_Piloto_Pessoa_CPF`)
    REFERENCES `TrabalhoISBD`.`Corrida` (`idcorrida` , `Passageiro_Pessoa_CPF` , `Piloto_Pessoa_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;